### ISSUE TITLE
Change log so that the work building the logged string is only done if we're going to use it.

### ISSUE THREAD

**Issue by cbrisebois** [coherence/log-dotnet#1]
Currently we can call these methods:
```
        public void Debug(string name, params object[] objects)
        {
            LogInternal(LogLevel.Debug, name, objects);
        }

        public void Info(string name, params object[] objects)
        {
            LogInternal(LogLevel.Info, name, objects);
        }

        public void Trace(string name, params object[] objects)
        {
            LogInternal(LogLevel.Trace, name, objects);
        }

        public void Warning(string name, params object[] objects)
        {
            LogInternal(LogLevel.Warning, name, objects);
        }
```
Brisk::Connector calls this when it sends a UDP packet: 
```
            if (octetsToSend.Length > 0)
            {
                log.Trace($"Sending packet {ByteArrayToString(octetsToSend)}");

                udpClient.Send(octetsToSend);
            }
```
The cost of converting a 1280 byte packet to a string is significant and a permanent overhead, but the value is only useful if someone is using trace logging which should only be a tiny portion of the time spent using the SDK.  So, I propose two options:

1. We don't set the trace level via a command line option so that we can have these functions compiled out via processor defines:
```
#define LOG_TRACE

        [Conditional(LOG_DEBUG)]
        public void Debug(string name, params object[] objects)
        {
            LogInternal(LogLevel.Debug, name, objects);
        }

        [Conditional(LOG_INFO)]
        public void Info(string name, params object[] objects)
        {
            LogInternal(LogLevel.Info, name, objects);
        }

        [Conditional(LOG_TRACE)]
        public void Trace(string name, params object[] objects)
        {
            LogInternal(LogLevel.Trace, name, objects);
        }

        [Conditional(LOG_WARNING)]
        public void Warning(string name, params object[] objects)
        {
            LogInternal(LogLevel.Warning, name, objects);
        }
```
Then we could set up conditions and defines that limit the amount of overhead the logs take.  Or

2. We use some delegate tricks for the logged values instead of processing the values then passing them in to be ignored.  But this will make the logging calls much more complex than log.Trace( STRING ) ...

log.ExampleTrace(()=> {return $"Sending packet {ByteArrayToString(octetsToSend)}"; })

There's probably some other tricks we could think of.

Additionally, the logging code itself is inefficient and causes allocations since it does this instead of using StringBuilder:
```
                    var fieldName = (string)objects[i];
                    s += " " + fieldName + "=";
                    var value = objects[i + 1];
                    if (value is int)
                    {
                        s = s + ((int)value).ToString();
                    }
                    else if (value is string)
                    {
                        s = s + ((string)value);

                    }
                    else if (value is float)
                    {
                        s = s + ((float)value).ToString();
                    }
                    else
                    {
                        s = s + value.ToString();
                    }
```

**Comment by rpadrela** [comment]
How useful is it to see `{ByteArrayToString(octetsToSend)}` in the log?

**Comment by rpadrela** [comment]
In regards to option #1, would the `Trace()` method be compiled out if the macro `LOG_TRACE` is not defined? If that's the case, what happens to all the `log.Trace()` calls? Will they be compiled out too?

**Comment by cbrisebois** [comment]
> How useful is it to see `{ByteArrayToString(octetsToSend)}` in the log?

it's useful to whoever added it, I guess.  I suspect no one is ever looking though.  I never even run trace (way too much data/don't know what I'm looking at)

**Comment by cbrisebois** [comment]
> In regards to option #1, would the `Trace()` method be compiled out if the macro `LOG_TRACE` is not defined? If that's the case, what happens to all the `log.Trace()` calls? Will they be compiled out too?

I **think** that it compiles out the calls at the caller level to address these kinds of things, so the log.Trace would not happen.  I would want to test it, though, if it's something we're interested in.

**Comment by rpadrela** [comment]
It doesn't hurt to have the possibility to compile them out if we want. I would question the usefulness of the `ByteArrayToString()` being printed to the log and would probably end up removing it as I doubt it's useful.
